apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: hamustra/api-test:latest
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: "development"
            - name: HOST
              value: "db-service"
            - name: DB_PORT
              value: "root"
            - name: USER
              value: "root"
            - name: PASSWORD
              value: "root"
            - name: DB
              value: "my_db"
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "200m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-server
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50